title: Eir Scaleform HUD
email: manups4e@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 API Documentation for the Eir HUD.
baseurl: "/EirHUD"
url: "https://manups4e.github.io/EirHUD"
github_username:  manups4e


# Build settings
remote_theme: just-the-docs/just-the-docs@v0.10.1
plugins:
  - jekyll-feed

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.12.0"



search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'
# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true
# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

color_scheme: dark

callouts:
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: purple



show_buttons: true
show_all_code: false
# For copy button on code
enable_copy_code_button: true

